# Generated by Django 5.0.1 on 2024-01-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='images'),
        ),
    ]
