# Generated by Django 5.0.1 on 2024-01-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_comment_commenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image3',
        ),
    ]
