# Generated by Django 5.0.1 on 2024-01-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_alter_blog_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
